config/routes.rb
Rails.application.routes.draw do
  resources :comments
  mount Ckeditor::Engine => '/ckeditor'
root to: 'visitors#new'
get 'download' => 'visitors#download'
get 'items' => 'visitors#items'
get 'dolacz' => 'visitors#invite'
get 'faq' => 'visitors#faq'
get 'technical-faq' => 'visitors#technicalfaq'
get 'admins/panel' => 'admins#panel'
get 'admins/new' => 'admins#new'
post 'admins/create' => 'admins#create'
get 'admins/useredit' => 'admins#useredit'
get 'calendars/index' => 'calendars#index'
post 'calendars/create' => 'calendars#create'
get 'calendars/new' => 'calendars#new'
get 'calendars/describe' => 'calendars#describe'
get 'zastepy' => 'units#index'
get 'units/create' => 'units#create'
post 'units/new' => 'units#new'
get 'sessions/new' => 'sessions#new'
post 'sessions/create' => 'sessions#create'
get 'sessions/logout' => 'sessions#destroy'
post 'users/create' => 'users#create'
get 'users/profile' => 'users#profile'
get 'users/new' => 'users#new'
get 'profil/edit' => 'users#edit'
patch 'profil/edited' => 'users#update'
get 'author' => 'users#author'
get 'posts/new' => 'posts#new'
post 'posts/create' => 'posts#create'
get '/post' => 'posts#show'
get '/post/edit' => 'posts#update'
post '/post/zedytowany' => 'posts#updated'
get 'posts/last2' => 'posts#last2'
get 'posts/kategoria' => 'posts#newcategory'
post '/post/dodanokategorie' => 'posts#categoryadded'
get 'posts/in' => 'posts#showcategory'
get 'galeria' => 'photos#show'
get 'galeria/dodaj' => 'photos#new'
get 'galeria/nowa' => 'photos#newgallery'
post 'galeria/dodano' => 'photos#create'
post 'galeria/dodanogalerie' => 'photos#creategallery'
get 'zdjecia/' => 'photos#showgallery'
get 'zdjecie/nowe' => 'photos#newingallery'
get 'zdjecie/nowe/dodaj' => 'photos#createingallery'
get 'contact' => 'contacts#index'
post 'contact/send' => 'contacts#create'
get 'kadra' => 'scouts#show'
get 'approve' => 'comments#approve'

resources :visitors do
  resources :posts
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	validates :zawartosc, length: {minimum: 5, maximum: 255}
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
	session[:return_to] ||= request.referer
    @comment = Comment.new(comment_params)
	id_postu = Post.select(:id).where(:tytul => params[:s]).first
	@comment.login = "#{current_user.imie} #{current_user.nazwisko}"
	@comment.id_dodajacego = current_user.id
	@comment.id_postu = id_postu.id
	if current_user.uprawnienia != "administrator"
	@comment.approved = "n"
	else
	@comment.approved = "y"
	end

    respond_to do |format|
      if @comment.save
		if @comment.approved = "n"
			format.html { redirect_to session.delete(:return_to), notice: 'Comment was successfully created and awaiting acceptaion.' }
			format.json { render :show, status: :created, location: @comment }
		else
			format.html { redirect_to session.delete(:return_to), notice: 'Comment was successfully created and awaiting acceptaion.' }
			format.json { render :show, status: :created, location: @comment }
		end
      else
        format.html { redirect_to session.delete(:return_to) }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def approve
	session[:return_to] ||= request.referer
	Comment.update(params[:id], :approved => "y")
	redirect_to session.delete(:return_to)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:zawartosc, :login, :id_postu)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<h1>Comments:</h1>
<% if @comments[0] == nil %>
No comments found!
<% else %>
<div id="comments-container">
    <% @comments.each do |comment| %>
	<div class="comment-container show-for-landscape">
	
		<div class="comment-author show-for-landscape">
			<%= image_tag (@user.avatar.url(:medium)), class: "comment-author-avatar show-for-landscape" %>
			<div class="comment-author-info show-for-landscape"><%= comment.login %>
			</div>
			<div class="comment-date show-for-landscape"><%= l(comment.created_at, :format => '%d %B %Y %H:%M:%S', :locale => 'en') %></div>
		</div>
		
		<div class="comment-content show-for-landscape">
			<%= simple_format(comment.zawartosc) %>
			
			<% if current_user != nil && current_user.uprawnienia == "administrator" %>
				<% if comment.approved == "n" %>
					<%= link_to "Zaakceptuj", {controller: "comments", action: "approve", id: comment.id}, style: "button" %>
				<% end %>
			<% end %>
		</div>
		
	</div>
	
	
	
	<div class="comment-container show-for-portrait">
	
		<div class="comment-author show-for-portrait">
			<%= image_tag (@user.avatar.url(:medium)), class: "comment-author-avatar show-for-portrait" %>
			<div class="comment-author-info show-for-portrait"><%= comment.login %></div>
			<div class="comment-date show-for-portrait"><%= l(comment.created_at, :format => '%d %B %Y %H:%M:%S', :locale => 'pl') %></div>
		</div>
		
		<div class="comment-content-small show-for-portrait">
			<%= simple_format(comment.zawartosc) %>	
		</div>
		
	</div>
	

	
    <% end %>
</div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add new comment:</h3>
<% if current_user == nil %>
You have to login in to add new comment!
If you don't have an account get it <%= link_to "here!", url: {controller: "users", action: "new"} %>
<% else %>
<%= simple_form_for @comment, :url =>{controller: "comments", action: "create", s: params[:s]} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
	
    <%= f.input :zawartosc, label: "Treść:", :input_html => { :onkeyup => "lenght()"} %>
	<div id="length-counter"> </div>
<% if current_user == nil %>
    <%= f.input :login %>
<% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add your comment!", class: "small secondary button" %>
  </div>
 <% end %>
<% end %>
<script type="text/javascript">
function lenght() {
var a = document.getElementById("comment_zawartosc").value
if (a.length < 5) {
	document.getElementById("length-counter").style.color = "red"
}
else if (a.length > 240 && a.length < 255) {
	document.getElementById("length-counter").style.color = "orange"
}
else if (a.length > 254) {
	document.getElementById("length-counter").style.color = "red"
}
else {
	document.getElementById("length-counter").style.color = "black"
}
document.getElementById("length-counter").innerHTML = "Limit: "+a.length+"/255"
}

</script>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Zawartosc</th>
      <th>Login</th>
      <th>Id postu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.zawartosc %></td>
        <td><%= comment.login %></td>
        <td><%= comment.id_postu %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zawartosc:</strong>
  <%= @comment.zawartosc %>
</p>

<p>
  <strong>Login:</strong>
  <%= @comment.login %>
</p>

<p>
  <strong>Id postu:</strong>
  <%= @comment.id_postu %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>