config/routes.rb
Rails.application.routes.draw do
  resources :comments
  mount Ckeditor::Engine => '/ckeditor'
root to: 'visitors#new'
get 'download' => 'visitors#download'
get 'items' => 'visitors#items'
get 'dolacz' => 'visitors#invite'
get 'faq' => 'visitors#faq'
get 'technical-faq' => 'visitors#technicalfaq'
get 'admins/panel' => 'admins#panel'
get 'admins/new' => 'admins#new'
post 'admins/create' => 'admins#create'
get 'admins/useredit' => 'admins#useredit'
get 'calendars/index' => 'calendars#index'
post 'calendars/create' => 'calendars#create'
get 'calendars/new' => 'calendars#new'
get 'calendars/describe' => 'calendars#describe'
get 'zastepy' => 'units#index'
get 'units/create' => 'units#create'
post 'units/new' => 'units#new'
get 'sessions/new' => 'sessions#new'
post 'sessions/create' => 'sessions#create'
get 'sessions/logout' => 'sessions#destroy'
post 'users/create' => 'users#create'
get 'users/profile' => 'users#profile'
get 'users/new' => 'users#new'
get 'profil/edit' => 'users#edit'
patch 'profil/edited' => 'users#update'
get 'author' => 'users#author'
get 'posts/new' => 'posts#new'
post 'posts/create' => 'posts#create'
get '/post' => 'posts#show'
get '/post/edit' => 'posts#update'
post '/post/zedytowany' => 'posts#updated'
get 'posts/last2' => 'posts#last2'
get 'posts/kategoria' => 'posts#newcategory'
post '/post/dodanokategorie' => 'posts#categoryadded'
get 'posts/in' => 'posts#showcategory'
get 'galeria' => 'photos#show'
get 'galeria/dodaj' => 'photos#new'
get 'galeria/nowa' => 'photos#newgallery'
post 'galeria/dodano' => 'photos#create'
post 'galeria/dodanogalerie' => 'photos#creategallery'
get 'zdjecia/' => 'photos#showgallery'
get 'zdjecie/nowe' => 'photos#newingallery'
get 'zdjecie/nowe/dodaj' => 'photos#createingallery'
get 'contact' => 'contacts#index'
post 'contact/send' => 'contacts#create'
get 'kadra' => 'scouts#show'
get 'approve' => 'comments#approve'

resources :visitors do
  resources :posts
end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
	@post = Post.all.last(6)
	@category = Category.all
	prepare_meta_tags(title: "Home")
  end
  
  def download
	prepare_meta_tags(title: "Download Pokemon Go", description: "Here you can easily download newest, secure version of Pokemon Go game.")
  end
  
  def items
	prepare_meta_tags(title: "Items in Pokemon Go", description: "Read about all known items in new Niantec Game - Pokemon Go. Learn how and when you can get special items.")
  end
  
  def faq
	prepare_meta_tags(title: "FAQ", description: "If you have any problem with Pokemon Go just check this page, if someone had any questions about game we replied here.")
  end
  
  def technicalfaq
	prepare_meta_tags(title: "Technical FAQ", description: "Is your phone supported by Pokemon Go? Is your system in good version? Everything about this here.")
  end
  
end

app/views/visitors/_highlight.html.erb
<div id="highlight" style="width:100%;min-height:43vh;height:350px;background: #e74c3c;float:left;margin-bottom:5px;text-align:center;" class="show-for-large-up">

	<div id="featured-posts" style="width:50%;height:43vh;float:left;display:inline-block;">
	
		<div id="featured-image" style="width:50%;float:left;min-height:350px;height:43vh; padding:15px;"> 
			<%= image_tag("/system/buttons/pikachuwelcome.png", style: "width:90%; height:105%;margin-top:-5px;") %>
		</div>
		
		<div id="featured-posts-title" style="font-size:2em;width:50%;float:left;display:inline-block;">Popular Articles:</div>
		
		<div id="featured-posts-list back" style="width:50%;float:left;height:43vh;min-height:350px;"> 
			<div class="featured-list-big"><i class="fi-wrench large" style="color:#f1c40f;padding:2px;"></i><%= link_to "First things to do in Pokemon Go", {controller: "posts", action: "show", s: "First things to do in Pokemon Go"}, style: "color: #34495e;" %></div>
			<div class="featured-list-big"><i class="fi-upload-cloud large" style="color:#f1c40f;padding:2px;"></i><%= link_to "10 Tips for Beggining Trainers", {controller: "posts", action: "show", s: "10 Tips for Beggining Trainers"}, style: "color: #34495e;" %></div>
			<div class="featured-list-big"><i class="fi-mountains large" style="color:#f1c40f;padding:2px;"></i><%= link_to "Frequently Asked Questions", {controller: "visitors", action: "faq"}, style: "color: #34495e;"%></div>
			<div class="featured-list-big"><i class="fi-lightbulb large" style="color:#f1c40f;padding:2px;"></i><%= link_to "How to take over Gyms and fight in it!", {controller: "posts", action: "show", s: "How to take over Gyms and fight in it"}, style: "color: #34495e;"%></div>
			<div class="featured-list-big"><i class="fi-star large" style="color:#f1c40f;padding:2px;"></i><%= link_to "PokeStops and awards for Visiting Them", {controller: "posts", action: "show", s: "PokeStops and awards for Visiting Them"}, style: "color: #34495e;" %></div>
		</div>
		
	</div>

	<div id="social-container" style="height:43vh;width:50%;float:left;display:inline-block;background-color:#c0392b;">
		<div id="twitter-container" class="show-for-medium-up"style="width:50%;float:left;height:43vh;min-height:350px;background-color:#c0392b;">
			<div id="twitter-header" style="font-size:2em;">Find us on Twitter:</div>
			<div id="twitter-page" style="min-height:350px;">
				<a class="twitter-timeline" data-height="38vh" data-theme="light" href="https://twitter.com/gopokemon24">Tweets by gopokemon24</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
			</div>
		</div>
		
		<div id="facebook-container" style="width:50%;float:left;display:inline-block;min-height:350px;background-color:#c0392b;">
			<div id="fb-header" style="font-size:2em;">Find us on Facebook:</div>
			<div id="fb-page">
				<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fgopokemon24&tabs=timeline&width=340&height=350&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="340" height="350" style="border:none;overflow:hidden;height:35vh;" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
			</div>
		</div>
		</div>
</div>

<div id="highlight" style="width:100%;min-height:400px;height:50vh;background: #e74c3c;float:left;margin-bottom:5px;text-align:center;" class="hide-for-large-up">

	<div id="featured-posts" style="width:100%;height:50vh;min-height:380px;float:left;display:inline-block;">
	
		<div id="featured-image" style="width:40%;float:left;min-height:380px;height:45vh;padding:15px;"> 
			<%= image_tag("/system/buttons/pikachuwelcome.png", style: "width:90%;height:45vh;min-height:380px;") %>
		</div>
		
		<div id="featured-posts-title" style="font-size:2em;width:60%;float:left;display:inline-block;">Popular Articles:</div>
		
		<div id="featured-posts-list back" style="width:60%;float:left;height:50vh;min-height:380px;"> 
		<div class="featured-list-small"><i class="fi-wrench large" style="color:#f1c40f;padding:2px;"></i><%= link_to "First things to do in Pokemon Go", {controller: "posts", action: "show", s: "First things to do in Pokemon Go"}, style: "color: #34495e;" %></div>
		<div class="featured-list-small"><i class="fi-upload-cloud large" style="color:#f1c40f;padding:2px;"></i><%= link_to "10 Tips for Beggining Trainers", {controller: "posts", action: "show", s: "10 Tips for Beggining Trainers"}, style: "color: #34495e;" %></div>
		<div class="featured-list-small"><i class="fi-mountains large" style="color:#f1c40f;padding:2px;"></i><%= link_to "Frequently Asked Questions", {controller: "visitors", action: "faq"}, style: "color: #34495e;"%></div>
		<div class="featured-list-small"><i class="fi-lightbulb large" style="color:#f1c40f;padding:2px;"></i><%= link_to "How to take over Gyms and fight in it!", {controller: "posts", action: "show", s: "How to take over Gyms and fight in it"}, style: "color: #34495e;"%></div>
		<div class="featured-list-small"><i class="fi-star large" style="color:#f1c40f;padding:2px;"></i><%= link_to "PokeStops and awards for Visiting Them", {controller: "posts", action: "show", s: "PokeStops and awards for Visiting Them"}, style: "color: #34495e;" %></div>
		</div>
		
	</div>
</div>

<style>
.featured-list-big {
min-height: 20%;
font-size:1.55em;
height:auto;
}
.featured-list-small {
min-height: 17.5%;
font-size:1.4em;
height:auto;
}

</style>

app/views/visitors/_sidebar.html.erb
<div id="sidebar">
<div class="insidebar" style="padding-left:10%;">
<b>Kategorie:</b>
<% @category.each do |f| %>
	<li><%= link_to f.nazwa, {controller: "posts", action: "showcategory", kategoria: f.nazwa} %></li>
<% end %>
</div>
<div class="insidebar" style="text-align:center;">
<p>Znajdź nas na Facebooku!</p>
<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FZHP.Sulecinek&tabs=messages&width=230&height=370&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" 
width="230" height="370" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true">
</iframe>
</div>

<div class="insidebar" style="text-align:center;">
<b>Warto sprawdzić:</br></b>
			<%= link_to "Galeria", {controller: "photos", action: "show"}, class: "button small secondary" %></br>
			<%= link_to "Kalendarz", calendars_index_path(rok: Time.now.year(), miesiac: Time.now.month()), class: "button small secondary" %></br>
			<%= link_to "Kadra", {controller: "scouts", action: "show"}, class: "button small secondary" %></br>
			<%= link_to "Kontakt", {controller: "contacts", action: "index"}, class: "button small secondary" %>
</div>

</div>


<style>
#sidebar {
float:right;
width:15%;
height:100vh;
background-color:#fdfdfd;
position:relative;
margin:0px;
margin-top:-15px;overflow:auto;
right:0px;
}
</style>

app/views/visitors/download.html.erb
<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-top -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="2820503107"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<div id="post-cover" style="margin:auto;width:80%;">
<%= image_tag "/system/buttons/download.png", class: "post-cover-image", style: "width:100%;height:65vh;" %>
</div>
<div class="post-title">How to install Pokemon Go?</div>
 <div class="post-content">
The game isn't published all over the world, so if you live in Europe it's impossible to download Pokemon Go from Apps Store or Google Play. If you are from America - just download the game from market!
 </br>
<b>How to install Pokemon Go from anywhere in the world?</b>
</br>
Follow these simple steps to install Pokemon Go in few minutes!
 </br>
<b>Installation on iOS:</b>

  <li>Logout from Apps Store!</li>
  <li>Open your web browser and go to Pokemon Go page in Apps Store!</li>
  <li>Switch your region into somewhere where Pokemon Go is published eg. America.</li>
  <li>Make new user account</li>
  <li>At registration you have to input address from choosen country(in our way it's United States)</li>
  <li>Download application on your phone</li>
  <li>Just login into your normal Apps Store account!</li>
  <li>Now you can run catch some Pokemons!</li>

 </br></br>

<b>Installation on Android system:</b>

   <li>Download .apk file with Pokemon Go game - be aware of viruses version so we recommend download it from there <%= link_to "APK Mirror", "http://www.apkmirror.com/apk/niantic-inc/pokemon-go/pokemon-go-0-29-0-release/pokemon-go-0-29-0-android-apk-download/" %></li>
   <li>Turn on installation from unknow sources in your Android</li>
   <li>Install the game from downloaded .apk.</li>
   <li>Now you can run catch some Pokemons!</li>

<b>Have you installed Pokemon Go but something don't work? Check out that your Mobile Phone fulfills system requirments of game: </b>
</br>
If you are using <b>Android</b> your system must be in version <b>4.4 or newer!</b>. You cannot play game with Intel Atom processor - it's not supported!<br>
If you have <b>Apple</b> device you have to use <b>iPhone 5</b> or newer with <b>iOS 8 and newer</b>! If your iPhone is Jailbroken you can't install this application!
<br>
<b>Also Android and iOS need stable internet and GPS connection to be able to play!</b>

<p style="text-align: center;"><strong>If you enjoyed this article - please Like our Fanpage - it will motivate us to write more about Pokemon Go!</strong></p>
<p style="text-align: center;"><iframe allowtransparency="true" frameborder="0" height="350" scrolling="no" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fgopokemon24&amp;tabs=timeline&amp;width=340&amp;height=350&amp;small_header=false&amp;adapt_container_width=true&amp;hide_cover=false&amp;show_facepile=true&amp;appId" style="border:none;overflow:hidden;height:35vh;" width="340"></iframe></p>
</div>
<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-bottom -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="4297236306"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

app/views/visitors/faq.html.erb
<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-top -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="2820503107"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

<div id="post-cover">
<%= image_tag "/system/buttons/faq.jpg", class: "post-cover-image", style: "width:100%;height:70vh" %>
</div>

<div class="post-title">Frequently Asked Question - find answer for your question!</div>
<div class="post-content">
<b>1. When Pokemon Go will be released in Europe?</b>
</br>
At this day there is no official date of release game in Europe.
</br></br>
<b>2. Which devices are supported by Pokemon Go?</b>
</br>
In theory every Android and iOS, but the fact is there is more requirements - we recommend to read about them in Technical FAQ.
</br></br>
<b>3. Is possible to exchange Pokemons with others?</b>
</br>
In current version of game this option is disabled, but this function is currently implemented in game. Exchange will be working with players at short distance around you and in players from the same team in Gym.
</br></br>
<b>4. Is Pokemon Go free?</b>
</br>
You can download and play game for free, but if you will want to grow your Pokemons faster there is some in-game payments.
</br></br>
<b>5. How much Internet Connection is used to play game?</b>
</br>
If you will download offline Google Maps i think 2GB will be enough to play a lot for one month. Your phone battery may die before it :P
</br></br>
<b>6. It's possible to catch Legendary Pokemons?</b>
</br>
Yes! At special events you will be able to catch some Legendary pokemons.
</br></br>
<b>7. How to evolve eevee?</b>
</br>
Use sweets, in the same way as with other pokemons. You have to collect required amount and click on evolution which is totaly random.
I'am sure you can find wild Vaporeon and other evolutions from 1'st series.
</br></br>
<b>8. Can I find other players on Map?</b>
</br>
At this day - no!
</br></br>
<b>9. Can i choose my starter pokemon?</b>
</br>
Yes. At the begining you will be able to choose one from three starters. Later you will be able to catch them as wild Pokemons but it's really rare.
</br></br>
<b>10. How PokeStops are working?</b>
</br>
You can read about PokeStops here.
</br></br>
<b>11. Can I fight with other trainers?</b>
</br>
Today it's disabled. But if you watched trailers there was shown 1vs1 and group fights.
</br></br>
<b>12. What is Pokemon Go Plus?</b>
</br>
It's special band in pokeball color. Middle button in this band will be vibrate in sequence when our phone is blocked. If player will repeat this sequence, an pokemon will be catched. You can find more about this here.
</br></br>
<b>13. Where I can catch Pokemons?</b>
</br>
They are located all over the world, just go walk around. They are spawned not only in urban area, so you can go to forest and find some!
</br></br>
<b>14. How to catch and evolve Pokemons?</b>
</br>
At start you need only to throw Poke Ball on Pokemon using green scope. Later you will need to throw more Poke Balls when scope is as small sa possible (orange or red). You don't have to fight with every Pokemon. To get EXP you need to catch as many as possible pokemons and evolve them.
For every Pokemon we are getting Candies and Stardust. Candies are used to evolve into next form, stardust with candy increases Combat Power(CP) of your pokemon.
So it's worth to catch every pokemon on our way because we can send them to professor and get candy (Transfer Option).
</br></br>
<b>15. Where I can get Pokeballs?</b>
</br>
You can buy them from in-game shop. But much cheaper option is visiting PokeStops where you can drop PokeBalls and Eggs and potions after 5 level.
</br></br>
<b>16. What I can do with Egg?</b>
</br>
We can make our own Pokemon! When we put an egg to Incubator we need to walk, or ride(max 20km/h) around to incubate our Pokemon. At later game stages we can get incubator which can incubate more eggs but break after 3 uses.
</br></br>
<b>17. How Poke Egg's are working?</b>
</br>
Everything about Poke Egg's here.
</br></br>
<b>18. Is pokemon have own level?</b>
</br>
No, there is no levels for pokemons. Real power of every pokemon is described by CP - as value of CP is higher as our Pokemon is stronger. Remember that higher trainer level making us able to catch stronger Pokemons. Use stardust and candies to add your pokemon some CP.
</br></br>
<b>19. How to evolve an pokemon?</b>
</br>
You will need candies - every pokemon needs different amount of candies to evolve. To evolve some pokemons you will need to collect candies assigned to his family.
</br></br>
<b>20. How many Pokemons we can carry?</b>
</br>
Probably all of them, but it's worth to send these unuseful to professor to get more candies.
</br></br>
<b>21. Can I fight with wild Pokemons?</b>
</br>
In this version of game no, but we hope it will be possible in future.
</br></br>
<b>22. How to use gyms and what I can get from them?</b>
</br>
After 5 level you will be able to fight in gym. At taking control over first gym you can choose your fraction(Yellows, Blues or Reds). White gyms are easy to take over because no one left there own pokemon. If gym is in your color you can add there your Pokemon to defend your honour!
It's worth to fight for the gyms because for every 21 hours gym under your control gives you 10 Poke Coins and about 500 Stardust.
</br></br>
<b>23. I cannot login into game?</b>
</br>
In last few days a lot of people want to play Pokemon Go. Game servers have problems with these crowds so sometimes it's impossible to play.
</br></br>
<b>24. It's better to login by Google or Pokemon Club?</b>
</br>
Logging in by Pokemon Club is not the best option, there is more problems with it than Google. <b>So we recommend logging in by Google!</b>


<p style="text-align: center;"><strong>If you enjoyed this article - please Like our Fanpage - it will motivate us to write more about Pokemon Go!</strong></p>
<p style="text-align: center;"><iframe allowtransparency="true" frameborder="0" height="350" scrolling="no" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fgopokemon24&amp;tabs=timeline&amp;width=340&amp;height=350&amp;small_header=false&amp;adapt_container_width=true&amp;hide_cover=false&amp;show_facepile=true&amp;appId" style="border:none;overflow:hidden;height:35vh;" width="340"></iframe></p>
</div>

<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-bottom -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="4297236306"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

app/views/visitors/invite.html.erb
<div id="invite">
	<div id="invite-cover">
	<h1> Dołącz do nas już dzisiaj!</h1>
	</div>
	Jak się z nami skontaktować?
	<H1>Napisz do nas na fejsbuku!</h1>
	<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FZHP.Sulecinek&tabs=messages&width=230&height=370&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" 
	width="230" height="370" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true">
	</iframe>
</div>
<style>
#invite {
width:100%;
height:100%;
}
#invite-cover {
position:relative;
width:100%;
height:50vh;
background: url("https://scontent-waw1-1.xx.fbcdn.net/v/t1.0-9/12494717_1759769774256242_7078185285230523305_n.jpg?oh=ff0fa93ef97050c5970670fb38f375a8&oe=583220D0") no-repeat fixed;
background-size: 100% 100%;
}
</style>

app/views/visitors/items.html.erb
<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-top -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="2820503107"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<div id="post-cover" style="margin:auto;width:80%;">
<%= image_tag "/system/buttons/all-items.jpg", class: "post-cover-image", style: "width:100%;height:65vh" %>
</div>
<div class="post-title">About all items in Pokemon Go</div>
<div class="post-content">
<b>In Pokemon Go</b> you can find different items, some of them will be given to you from the begining, other you can find walking around streets and visiting PokeStops. But if you want more items you can buy them in Shop. Anyway - below you can find a list of all known items in Pokemon Go world:
</br></br>
<b>Purchasable Items - </b>You can find all of theese items in Pokemon Go Shop - only thing which you need to buy them is enough Pokecoins. It's also possible to find them in Poke Stops, but you never know where and when.
</br>
<b>Poke Balls</b>
</br>
Poke Ball is something which you as trainer you must use the most - or not.. But who is a trainer without pokemons? At start you have 50 Poke Balls - you can get more at Poke Stops and Go Shop. Getting levels may drop you new pokeballs - remember about this :)
</br></br>
<b>Incense</b>
</br>
Use incense to find hidden Pokemons and increase chance to find hiding pokemons in the wild for at least 30 minutes of use. At begin you have two Incenses and you can get more with PokeCoins.
</br></br>
<b>Egg Incubator</b>
</br>
If you put an Egg in Egg Incubator you will be delivered to travel some distance with phone GPS before the egg will hatch. You have one incubator, but you can reuse it as many times as you want. You can get better versions of Incubator which can incubate multiple eggs by leveling or buying it in Store.
But this version of Incubator will break after 3 uses.
</br></br>
<b>Lucky Eggs</b>
</br>
Lucky Eggs are used to give you double experience boost for 30 minutes. You use it when you want, and when you want more of them visit GoShop and spend some PokeCoins!
</br></br>
<b>Lure Module</b>
</br>
A Lure Module is upgraded version of incense that attracts Pokemon to a particular PokeStop for a 30 minutes. It's not only more effective than incense, but it also works globally - targets the PokeStop for everyone, every players interacting with choosen PokeStop is affected during these 30 minutes!
</br></br>
<b>Bag</b>
</br>
If we have all above items we need to store them somewhere, and exactly for this purpuose is your Bag. At start you can carry up to 350 different items, but you can but Bag Upgrade which gives you 50 more places for items per upgrade.
</br></br>
<b>Pokemon Storage</b>
</br>
It's used to store all of your catched pokemons. At start everyone can have 250 different Pokemons with 9 Pokemons Eggs. Upgrades works in the same way as in your Bag - every gives you space for 50 more pokemons.
</br></br></br>
<b>Collectible Items - </b> It's impossible to buy everything in the shop, sometimes you will have to visit your local PokeStops to obtain new valuable items like them:
</br></br>
<b>Revive and Max Revive</b>
</br>
Use revive when your Pokemon is fainted, and it's will bring 50% of pokemon HP back. Max Revive works almost the same, but bringing back 100% of fainted Pokemon HP. Remember that Pokemon may be fainted in Gym Battle against opposing gym teams only.
</br>
Revives are basically dropped from PokeStops after you as trainer obtain 5 level.
</br></br>
<b>Potions</b>
</br>
There is nothing special - if you have ever played video games you know how Potions works. Only thing which you need to know is that you can find them in PokeStops after level 5. Leveling up should give you some potions. Known types of Potions in Pokemon Go:
Super Potions will start appearing in PokeStops after level 10, and will also be given as level 10+ rewards.
</br>
    <b>Potion</b> - Gives you additional <b>20 HP</b> points.</br>
    <b>Super Potion</b> - Gives you additional <b>50 HP</b> points. </br>
    <b>Hyper Potion</b> - Gives you additional <b>200 HP</b> points.</br>
</br>
</br>
<b>Razz Berry</b>
</br>
After 8 level you will be able to find Razz Berries - it's used to feed catching Pokemon. Feeded pokemon is easier to catch in next throw - so don't lose this!
</br></br>
<b>Great Balls and Ultra Balls</b>
</br>
Great Ball is upgraded version of Poke Ball, you can buy them in the shop or find at PokeStops. You will be able to find them after 12 in-game level.
</br>
After level 20 you will be able to find <b>Ultra Balls</b> which are best known version of Poke Ball.
</br>
</br>
<b>Stardust</b>
</br>
Used to evolving Pokemons and making them stronger. We can drop some Stardust at catching pokemons and when we take control over gym for more than 21 hours.
</br>
</br>
</br>
<b>Other Items</b>
</br>
These items are given to every trainer, and cannot be purchased.
</br>
<b>Camera</b>
</br>
Given to you from the begining of your story, it bringing you possibility to photograph Pokemons in their natural street enviroment.
This item is automatically given to you at the start of your adventure, and allows you to easily photograph your encounter with a Pokemon in the wild. Just tap the camera icon during an encounter! 

<p style="text-align: center;"><strong>If you enjoyed this article - please Like our Fanpage - it will motivate us to write more about Pokemon Go!</strong></p>
<p style="text-align: center;"><iframe allowtransparency="true" frameborder="0" height="350" scrolling="no" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fgopokemon24&amp;tabs=timeline&amp;width=340&amp;height=350&amp;small_header=false&amp;adapt_container_width=true&amp;hide_cover=false&amp;show_facepile=true&amp;appId" style="border:none;overflow:hidden;height:35vh;" width="340"></iframe></p>
</div>
<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-bottom -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="4297236306"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

app/views/visitors/new.html.erb
</br>
<%= render :partial => 'highlight' %>
</br>

<%= render :partial => '/posts/last' %>

<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-bottom -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="4297236306"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>