config/routes.rb
Rails.application.routes.draw do
  resources :comments
  mount Ckeditor::Engine => '/ckeditor'
root to: 'visitors#new'
get 'download' => 'visitors#download'
get 'items' => 'visitors#items'
get 'dolacz' => 'visitors#invite'
get 'faq' => 'visitors#faq'
get 'technical-faq' => 'visitors#technicalfaq'
get 'admins/panel' => 'admins#panel'
get 'admins/new' => 'admins#new'
post 'admins/create' => 'admins#create'
get 'admins/useredit' => 'admins#useredit'
get 'calendars/index' => 'calendars#index'
post 'calendars/create' => 'calendars#create'
get 'calendars/new' => 'calendars#new'
get 'calendars/describe' => 'calendars#describe'
get 'zastepy' => 'units#index'
get 'units/create' => 'units#create'
post 'units/new' => 'units#new'
get 'sessions/new' => 'sessions#new'
post 'sessions/create' => 'sessions#create'
get 'sessions/logout' => 'sessions#destroy'
post 'users/create' => 'users#create'
get 'users/profile' => 'users#profile'
get 'users/new' => 'users#new'
get 'profil/edit' => 'users#edit'
patch 'profil/edited' => 'users#update'
get 'author' => 'users#author'
get 'posts/new' => 'posts#new'
post 'posts/create' => 'posts#create'
get '/post' => 'posts#show'
get '/post/edit' => 'posts#update'
post '/post/zedytowany' => 'posts#updated'
get 'posts/last2' => 'posts#last2'
get 'posts/kategoria' => 'posts#newcategory'
post '/post/dodanokategorie' => 'posts#categoryadded'
get 'posts/in' => 'posts#showcategory'
get 'galeria' => 'photos#show'
get 'galeria/dodaj' => 'photos#new'
get 'galeria/nowa' => 'photos#newgallery'
post 'galeria/dodano' => 'photos#create'
post 'galeria/dodanogalerie' => 'photos#creategallery'
get 'zdjecia/' => 'photos#showgallery'
get 'zdjecie/nowe' => 'photos#newingallery'
get 'zdjecie/nowe/dodaj' => 'photos#createingallery'
get 'contact' => 'contacts#index'
post 'contact/send' => 'contacts#create'
get 'kadra' => 'scouts#show'
get 'approve' => 'comments#approve'

resources :visitors do
  resources :posts
end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	EMAIL_REGEX = /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/
	validates :login, :presence => true, :uniqueness => true, :length => { :in => 3..20 }, on: :create
	validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX, on: :create
	validates :password, :presence => true, :confirmation => true, length: { :in => 6..50,
	    too_short: "The password must have at least %{count} characters.",
		too_long: "The password must have no more than %{count} characters.",
		}, on: :create
	validates :password_confirmation, :presence => true, :confirmation => true, length: { :in => 6..50,
	    too_short: "The password must have at least %{count} characters.",
		too_long: "The password must have no more than %{count} characters.",
		}, on: :create
	validates_presence_of :imie, :nazwisko, :password, on: :create
	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },	
	:path => ":rails_root/public/system/:attachment/:id/:style/:filename",    
	:url => "/system/:attachment/:id/:style/:filename"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	
	
	def combined_value
		"#{self.imie} #{self.nazwisko}"
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@users = User.new
		prepare_meta_tags(title: "Register", description: "Sign up to our website here.")
	end
	
	def create
		@users = User.new(secure_params)
			if @users.valid?
				@users.save
				id = User.select(:id).where(:login => params[:user][:login]).first
				@users = User.update(id.id, :uprawnienia => "uzytkownik", :isadmin => "n")
				flash[:notice] = "Zarejestrowano użytkownika #{@users.login}"
				redirect_to sessions_new_path
			else
				flash[:notice] = "Wystapil blad #{@users.login}"
				render 'new'
			end
	end
	
	def profile
		@user = User.where(:login => params[:login]).first
		prepare_meta_tags(title: "#{@user.login} profile.", description: "##{@user.login} profile.")
	end
	
	def author
		@post = Post.where(:id_autora => params[:id])
		@user = User.find(params[:id])
		prepare_meta_tags(title: "Published by #{@user.login}", description: "#All posted by #{@user.login}.")
	end
	
	def edit
		@user = User.where(:login => params[:user]).first
	end
	
	def update
		session[:return_to] ||= request.referer
		id = User.select(:id).where(:id => params[:user][:id]).first
		@user = User.update(id.id, update_params)
		flash[:notice] = "Twój profil został pomyślnie zaaktualizowany!"
		redirect_to session.delete(:return_to)
	end
	
private

	def secure_params
		params.require(:user).permit(:login, :email, :password, :password_confirmation, :password_digest, :imie, :nazwisko)
	end
	
	def update_params
		params.require(:user).permit(:password, :password_confirmation, :password_digest, :imie, :nazwisko, :avatar, :description)
	end
	
end

app/views/users/author.html.erb
<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-top -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="2820503107"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

<%= render :partial => "posts/articlebox" %>

<div id="inpost-ad-container">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- pokemongo-bottom -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-6222054838117933"
     data-ad-slot="4297236306"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>

app/views/users/create.html.erb
<%= simple_form_for(@users, url: users_create_path) do |form| %>
<%= form.error_notification %>
<%= form.input :email %>
<%= form.input :login %>

<%= form.label :password %>
<%= form.password_field :password %>

<%= form.label :password_confirmation %>
<%= form.password_field :password_confirmation %>

<%= form.input :imie %>
<%= form.input :nazwisko %>
<%= form.button :submit, 'Zarejestruj się!', class: 'submit' %>
<% end %>

<%= link_to "Zaloguj się", {controller: "sessions", action: "new"}, class: "button" %>

app/views/users/edit.html.erb
<%= simple_form_for @user, url: {controller: "users", action: "update"}, html: { multipart: true } do |form| %>
<%= form.error_notification %>

<%= form.hidden_field :id %>

<%= form.label :password %>
<%= form.password_field :password %>

<%= form.label :password_confirmation %>
<%= form.password_field :password_confirmation %>

<%= form.input :imie %>
<%= form.input :nazwisko %>

<%= form.label :description, "Opis:" %>
<%= form.cktext_area :description, :ckeditor => {:language => 'pl'} %>

<%= form.label :avatar, "Dodaj Awatar" %>
<%= form.file_field :avatar %>

<%= form.button :submit, 'Zaaktualizuj profil!', class: 'submit' %>
<% end %>

app/views/users/new.html.erb
<%= simple_form_for(@users, url: users_create_path) do |form| %>
<%= form.error_notification %>
<%= form.input :email %>
<%= form.input :login %>

<%= form.label :password %>
<%= form.password_field :password %>

<%= form.label :password_confirmation %>
<%= form.password_field :password_confirmation %>

<%= form.input :imie %>
<%= form.input :nazwisko %>
<%= form.button :submit, 'Zarejestruj się!', class: 'submit secondary button' %>
<% end %>

app/views/users/profile.html.erb
</br>
<div class="avatar" style="width:200px;height:200px;margin:auto; float:left; margin:10px;">
	<%= image_tag @user.avatar.url(:medium), style: "width:100%;height:100%;" %>
</div>
<h2><%= @user.imie %> <%= @user.nazwisko %></h2>
<h3><%= @user.login %></h3></br>
<h4>About me:<%= simple_format @user.description %>
<% if @user.uprawnienia != "uzytkownik" %>
<%= link_to "Napisz nowy post!", {controller: "posts", action: "new"} %>
<% end %>
<%= link_to "Edit Profile", {controller: "users", action: "edit", user: params[:login]}, style: "secondary button" %>
aasd