config/routes.rb
Rails.application.routes.draw do
  resources :comments
  mount Ckeditor::Engine => '/ckeditor'
root to: 'visitors#new'
get 'download' => 'visitors#download'
get 'items' => 'visitors#items'
get 'dolacz' => 'visitors#invite'
get 'faq' => 'visitors#faq'
get 'technical-faq' => 'visitors#technicalfaq'
get 'admins/panel' => 'admins#panel'
get 'admins/new' => 'admins#new'
post 'admins/create' => 'admins#create'
get 'admins/useredit' => 'admins#useredit'
get 'calendars/index' => 'calendars#index'
post 'calendars/create' => 'calendars#create'
get 'calendars/new' => 'calendars#new'
get 'calendars/describe' => 'calendars#describe'
get 'zastepy' => 'units#index'
get 'units/create' => 'units#create'
post 'units/new' => 'units#new'
get 'sessions/new' => 'sessions#new'
post 'sessions/create' => 'sessions#create'
get 'sessions/logout' => 'sessions#destroy'
post 'users/create' => 'users#create'
get 'users/profile' => 'users#profile'
get 'users/new' => 'users#new'
get 'profil/edit' => 'users#edit'
patch 'profil/edited' => 'users#update'
get 'author' => 'users#author'
get 'posts/new' => 'posts#new'
post 'posts/create' => 'posts#create'
get '/post' => 'posts#show'
get '/post/edit' => 'posts#update'
post '/post/zedytowany' => 'posts#updated'
get 'posts/last2' => 'posts#last2'
get 'posts/kategoria' => 'posts#newcategory'
post '/post/dodanokategorie' => 'posts#categoryadded'
get 'posts/in' => 'posts#showcategory'
get 'galeria' => 'photos#show'
get 'galeria/dodaj' => 'photos#new'
get 'galeria/nowa' => 'photos#newgallery'
post 'galeria/dodano' => 'photos#create'
post 'galeria/dodanogalerie' => 'photos#creategallery'
get 'zdjecia/' => 'photos#showgallery'
get 'zdjecie/nowe' => 'photos#newingallery'
get 'zdjecie/nowe/dodaj' => 'photos#createingallery'
get 'contact' => 'contacts#index'
post 'contact/send' => 'contacts#create'
get 'kadra' => 'scouts#show'
get 'approve' => 'comments#approve'

resources :visitors do
  resources :posts
end

end

app/views/layouts/_footer.html.erb
<div class="footer">
            <li><%= link_to "Home", root_path %></li>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">



<nav class="menu">

  <h1 class="name"><i><%= image_tag("/system/buttons/pika.png", style: "width:40px;height:40px;margin-top:-10px;") %></i>GO Pokemon 24</a></h1>

  <ul class="inline-list">

    <li><%= link_to "Home", root_path %></li>

    <li class="active"><%= link_to "How to play?", {controller: "posts", action: "showcategory", category: "Tutorials"} %></li>
	
	<li><%= link_to "Download", {controller: "visitors", action: "download"} %></li>

    <li><%= link_to "All Items", {controller: "visitors", action: "items"} %></li>
		  
    <li><%= link_to "FAQ", {controller: "visitors", action: "faq"} %></li>
	
	<li><%= link_to "Technical FAQ", {controller: "visitors", action: "technicalfaq"} %></li>

     <li><%= link_to "Contact", {controller: "contacts", action: "index"} %></li>

  </ul>

  <ul class="inline-list hide-for-small-only account-action">
  
  <%= render 'layouts/navigation_links' %>

<% if @current_user == nil %>
    <li><a href="#" data-reveal-id="myModal">Login</a></li>

    <li class=""><a class="signup" href="#" data-reveal-id="myModal">Signup</a></li>
<% end %>

  </ul>

  <a class="account hide-for-medium-up" href="#" data-reveal-id="myModal"><i class="fi-unlock"></i></a>

</nav>



<!-- modal content -->



<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="login or sign up" aria-hidden="true" role="dialog">

  <div class="row">

    <div class="large-6 columns auth-plain">

      <div class="signup-panel left-solid">

        <p class="welcome">Registered Users</p>

          <div class="row collapse">

            <div class="small-2  columns">

              <span class="prefix"><i class="fi-torso-female"></i></span>

            </div>

            <div class="small-10  columns">
			<%= simple_form_for(:session, url: sessions_create_path) do |form| %>
			<%= form.error_notification %>
			
			<%= form.input :email, label: false, placeholder: "e-mail" %>

            </div>

          </div>

          <div class="row collapse">

            <div class="small-2 columns ">

              <span class="prefix"><i class="fi-lock"></i></span>

            </div>

            <div class="small-10 columns ">

              <%= form.password_field :password, placeholder: "password" %>

            </div>

          </div>

		<%= form.button :submit, 'Log In', class: 'button submit' %>
		<% end %>

      </div>

    </div>



    <div class="large-6 columns auth-plain">

    	<div class="signup-panel newusers">

    		<p class="welcome"> New User?</p>

    		<p>By creating an account with us, you will be able to move through the checkout process faster, view and track your orders, and more.</p><br>

    		<%= link_to "Sign Up", {controller: "users", action: "new"}, class: "button" %></br>

    	</div>

    </div>



   </div>

  <a class="close-reveal-modal" aria-label="Close">&#215;</a>

</div>

app/views/layouts/_navigation_links.html.erb
<% if logged_in? %>
<%= link_to "Logout!", {controller: "sessions", action: "destroy"}, class: "button small alert" %></li>
<li>  <%= link_to "My profile!", {controller: "users", action: "profile", login: @current_user.login}, class: "button small confirm" %></li>
<% else %>

<% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  <%= display_meta_tags %>
  
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<script>
		(adsbygoogle = window.adsbygoogle || []).push({
		google_ad_client: "ca-pub-6222054838117933",
		enable_page_level_ads: true
		});
	</script>
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
		
		ga('create', 'UA-59949924-2', 'auto');
		ga('send', 'pageview');
		
	</script>
  <%= favicon_link_tag '/system/buttons/favicon.ico', type: 'image/ico' %>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
	<script type="text/javascript">
	$(document).foundation();
	</script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
  </head>

  <body>
    <div class="title-bar" data-responsive-toggle="nav-menu" data-hide-for="medium">
      <%= render 'layouts/navigation' %>
    </div>
<div id="wrap">
    <main role="main">
      <%= render 'layouts/messages' %>
		<%= yield %>
    </main>
</div>
    
    <%= javascript_include_tag "application" %>
	 <%= render 'layouts/footer' %>
  </body>
</html>